name: Astronomer CI - Deploy code to Astro

on:
  push:
    branches:
      - demo/astro-essentials

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Astro
      uses: astronomer/deploy-action@v0.11.0
      with:
        deployment-id: cmk5pzcao0u8q01ksnefke02c